apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: logengine
spec:
  clusterIP: None
  selector:
    app: node
  ports:
  - name: grpc
    port: {{ .Values.node.grpcPort }}
  - name: metrics
    port: {{ .Values.node.metricsPort }}
