FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /node ./cmd/node

FROM alpine:3.19
COPY --from=builder /node /node
ENTRYPOINT ["/node"]
