global:
  scrape_interval: 15s

scrape_configs:
  - job_name: coordinators
    static_configs:
      - targets:
          - coordinator-1:8080
          - coordinator-2:8080
          - coordinator-3:8080

  - job_name: nodes
    static_configs:
      - targets:
          - node-1:9090
          - node-2:9090
          - node-3:9090
